server:
  port: 9091

spring:
  application:
    name: NextFirstFiltrex

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=filtrex_db;encrypt=true;trustServerCertificate=true
    username: mssql
    password: mssql
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 6
    locations: classpath:db/migration
    table: schema_version
    validate-on-migrate: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: anil.p@nextfirst.com
    password: zkee fllq kotx ctrj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

report:
  email:
    enabled: true
    to: anilnpatil143@gmail.com
    subject: Filtrex shift report
    body: Please find attached the shift report.
